### ISSUE TITLE
When source text is deleted translation still persists

### ISSUE THREAD

**Issue by IllyaHavrulyk** [IllyaHavrulyk/leolang-frontend#19]
When source text is deleted translation still persists

https://github.com/IllyaHavrulyk/leolang-frontend/assets/33462649/80a0475c-37c1-419c-80b7-ca8421362627

**Comment by bigheha** [comment]
Fixed, there is still a short animation after source text deletion, but it has nothing to do with API request. This occures because of how Redux handles async actions. Might look for workarounds in future
